### ISSUE TITLE
release without warnings-as-errors?

### ISSUE THREAD

**Issue by avsm** [incubaid/baardskeerder#7]
The 0.5.1 release has warnings as errors, which means compilation with ocaml 4.01 fails:

```
# + ocamlfind ocamlc -c -g -annot -w A -warn-error A -thread -package oUnit -package quickcheck -package lwt.preemptive -package lwt.unix -package lwt -o flog_test.cmo flog_test.ml
# File "flog_test.ml", line 30, characters 0-11:
# Warning 44: this open statement shadows the value identifier close (which is later used)
# File "flog_test.ml", line 1:
# Error: Some fatal warnings were triggered (1 occurrences)
```

Any chance of a release with this option disabled?

**Comment by avsm** [comment]
xref to OPAM triage run ocaml/opam-repository#1304

**Comment by toolslive** [comment]
this is a trivial fix. will do this shortly.

On Friday, December 20, 2013 3:41 AM, Anil Madhavapeddy notifications@github.com wrote:

The 0.5.1 release has warnings as errors, which means compilation with ocaml 4.01 fails:

# \+ ocamlfind ocamlc -c -g -annot -w A -warn-error A -thread -package oUnit -package quickcheck -package lwt.preemptive -package lwt.unix -package lwt -o flog_test.cmo flog_test.ml

# File "flog_test.ml", line 30, characters 0-11:

# Warning 44: this open statement shadows the value identifier close (which is later used)

# File "flog_test.ml", line 1:

# Error: Some fatal warnings were triggered (1 occurrences)

Any chance of a release with this option disabled?

**Comment by toolslive** [comment]
compiles without warnings in 0.5.2 which is cleaner than  'release without warnings-as-errors'

**Comment by toolslive** [comment]
you can find the  opam package for this, here:
https://github.com/Incubaid/opam-repository-devel/commit/f1f5fba168e6c6b094de37b5cacd14fd659aac30

**Comment by avsm** [comment]
Thanks for the quick response! I've imported it into the main repo as ocaml/opam-repository#1479. Only tweak is to add a lower bound to Lwt to ensure the bugfixes needed by the package are picked up.

**Comment by toolslive** [comment]
tx, I will add that Lwt requirement in our devel repo as well.

**Comment by avsm** [comment]
Darn, it now it fails on MacOS due to the `-Werror` added to CCopt in `myocamlbuild.ml`.  There's a bogus clang warning that triggers the failure.

```
+ ocamlfind ocamlc -ccopt -Wall -ccopt -Wextra -ccopt -Werror -ccopt -O3 -ccopt -I.. -ccopt -msse4.2 -I /Users/avsm/.opam/system/lib/lwt -c posix.c
clang: error: argument unused during compilation: '-fno-defer-pop'
```

**Comment by toolslive** [comment]
would it help if I just remove the -Werror ?

**Comment by avsm** [comment]
Yeah it would be easier not to have it.

**Comment by toolslive** [comment]
0.5.3
& package description is here:
https://github.com/Incubaid/opam-repository-devel/tree/master/packages/baardskeerder.0.5.3
